CREATE DATABASE applicant;
CREATE DATABASE investigator;
CREATE DATABASE assessor;
CREATE DATABASE manager;
CREATE DATABASE gatherer;
CREATE DATABASE scholar;
CREATE DATABASE assistant;
CREATE DATABASE designer;
